#!/usr/bin/env python3
"""
Environment Setup Script
This script helps set up environment variables for the portfolio app
"""

import os
import secrets

def generate_secret_key():
    """Generate a secure secret key"""
    return secrets.token_hex(32)

def create_env_file():
    """Create or update .env file with required variables"""
    env_content = f"""# Flask Configuration
FLASK_ENV=development
DEBUG=True
SECRET_KEY={generate_secret_key()}

# Admin Panel Credentials
ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin1234

# GitHub Integration
GITHUB_USERNAME=Zarifwebme

# Database (SQLite will be created automatically)
# DATABASE_URL=sqlite:///instance/portfolio.db

# Server Configuration
# PORT=5000
# HOST=0.0.0.0
"""
    
    env_file = ".env"
    
    if os.path.exists(env_file):
        print(f"⚠️  .env file already exists. Creating backup as .env.backup")
        os.rename(env_file, f"{env_file}.backup")
    
    try:
        with open(env_file, "w") as f:
            f.write(env_content)
        print(f"✅ Created {env_file} with all required environment variables")
        return True
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        return False

def show_env_content():
    """Display the environment variables that will be set"""
    print("\n🔧 Environment Variables to be set:")
    print("=" * 50)
    print("FLASK_ENV=development")
    print("DEBUG=True")
    print("SECRET_KEY=<auto-generated>")
    print("ADMIN_USERNAME=admin")
    print("ADMIN_PASSWORD=admin1234")
    print("GITHUB_USERNAME=Zarifwebme")
    print("\n📝 Note: SECRET_KEY will be automatically generated")

def main():
    print("🚀 Portfolio App Environment Setup")
    print("=" * 50)
    
    # Show what will be configured
    show_env_content()
    
    # Ask for confirmation
    response = input("\n❓ Do you want to create/update the .env file? (y/n): ").lower()
    
    if response in ['y', 'yes']:
        if create_env_file():
            print("\n🎉 Environment setup complete!")
            print("\n📝 Next steps:")
            print("1. Start your Flask application")
            print("2. Access admin panel at: http://localhost:5000/login")
            print("3. Login with: admin / admin1234")
            print("4. Start managing your portfolio content!")
        else:
            print("\n❌ Environment setup failed. Please check the errors above.")
    else:
        print("\n⏭️  Setup cancelled. You can manually create the .env file.")
        print("Copy the variables shown above into your .env file.")

if __name__ == "__main__":
    main()
